TextInputXpath='xpath://input[@title="Search"]'
SearchButtonXpath='xpath://input[@class="gNO89b"]'
ClickLinkXpath='xpath://a/h3'
GoogleLogoXpath='xpath://img[@class="lnXdpd"]'
TextSearchResultXpath='xpath://title[contains(text(),"Google Search")]'
ParentNode='xpath://a/h3//parent::a'
ElementXpath='xpath://h1[contains(text(),"Find your dream job now")]'