TextInputXpath='xpath://input[@title="Search"]'
SearchButtonXpath='xpath://input[@class="gNO89b"]'
ClickLinkXpath='xpath://div[@class="CCgQ5 vCa9Yd QfkTvb MUxGbd v0nnCb"]'
GoogleLogoXpath='xpath://img[@class="lnXdpd"]'
TextSearchResultXpath='xpath://title[contains(text(),"Google Search")]'